/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expenses.gui;

import expenses.pojo.GlobalData;

/**
 *
 * @author Maraxys
 */
public class CategorySelectionFrame extends javax.swing.JFrame {

    /**
     * Creates new form CategorySelectionFrame
     */
    String cCat,cResult,cDesc;
    //String cDate;
    
    public CategorySelectionFrame() {
        initComponents();
        super.setLocationRelativeTo(null);
    }
    
    public CategorySelectionFrame(String calResult,String desc) {
      
        this();
        //cDate=date;
        cResult=calResult;
        cDesc=desc;
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelHealth = new javax.swing.JPanel();
        lblHealth = new javax.swing.JLabel();
        panelBills = new javax.swing.JPanel();
        lblBills = new javax.swing.JLabel();
        panelEdu = new javax.swing.JPanel();
        lblEducation = new javax.swing.JLabel();
        panelGrocery = new javax.swing.JPanel();
        lblGrocery = new javax.swing.JLabel();
        panelTravel = new javax.swing.JPanel();
        lblTravel = new javax.swing.JLabel();
        panelEntertain = new javax.swing.JPanel();
        lblEnt = new javax.swing.JLabel();
        panelShopping = new javax.swing.JPanel();
        lblShopping = new javax.swing.JLabel();
        panelOthers = new javax.swing.JPanel();
        lblOthers = new javax.swing.JLabel();
        panelEatout = new javax.swing.JPanel();
        lblEatout = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelHealth.setBackground(new java.awt.Color(0, 0, 204));
        panelHealth.setForeground(new java.awt.Color(255, 255, 255));
        panelHealth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelHealth.setPreferredSize(new java.awt.Dimension(175, 175));
        panelHealth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelHealthMouseClicked(evt);
            }
        });

        lblHealth.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lblHealth.setForeground(new java.awt.Color(255, 255, 255));
        lblHealth.setText("Health");

        javax.swing.GroupLayout panelHealthLayout = new javax.swing.GroupLayout(panelHealth);
        panelHealth.setLayout(panelHealthLayout);
        panelHealthLayout.setHorizontalGroup(
            panelHealthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHealthLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblHealth)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        panelHealthLayout.setVerticalGroup(
            panelHealthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHealthLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(lblHealth)
                .addGap(25, 25, 25))
        );

        panelBills.setBackground(new java.awt.Color(0, 0, 204));
        panelBills.setForeground(new java.awt.Color(255, 255, 255));
        panelBills.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBills.setPreferredSize(new java.awt.Dimension(175, 175));
        panelBills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBillsMouseClicked(evt);
            }
        });

        lblBills.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lblBills.setForeground(new java.awt.Color(255, 255, 255));
        lblBills.setText("Bills");

        javax.swing.GroupLayout panelBillsLayout = new javax.swing.GroupLayout(panelBills);
        panelBills.setLayout(panelBillsLayout);
        panelBillsLayout.setHorizontalGroup(
            panelBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillsLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblBills)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panelBillsLayout.setVerticalGroup(
            panelBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBillsLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(lblBills)
                .addGap(23, 23, 23))
        );

        panelEdu.setBackground(new java.awt.Color(0, 0, 204));
        panelEdu.setForeground(new java.awt.Color(255, 255, 255));
        panelEdu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEdu.setPreferredSize(new java.awt.Dimension(175, 175));
        panelEdu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEduMouseClicked(evt);
            }
        });

        lblEducation.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lblEducation.setForeground(new java.awt.Color(255, 255, 255));
        lblEducation.setText("Education");

        javax.swing.GroupLayout panelEduLayout = new javax.swing.GroupLayout(panelEdu);
        panelEdu.setLayout(panelEduLayout);
        panelEduLayout.setHorizontalGroup(
            panelEduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEduLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lblEducation)
                .addGap(42, 42, 42))
        );
        panelEduLayout.setVerticalGroup(
            panelEduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEduLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(lblEducation)
                .addGap(34, 34, 34))
        );

        panelGrocery.setBackground(new java.awt.Color(0, 0, 204));
        panelGrocery.setForeground(new java.awt.Color(255, 255, 255));
        panelGrocery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelGrocery.setPreferredSize(new java.awt.Dimension(175, 175));
        panelGrocery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelGroceryMouseClicked(evt);
            }
        });

        lblGrocery.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lblGrocery.setForeground(new java.awt.Color(255, 255, 255));
        lblGrocery.setText("Grocery");

        javax.swing.GroupLayout panelGroceryLayout = new javax.swing.GroupLayout(panelGrocery);
        panelGrocery.setLayout(panelGroceryLayout);
        panelGroceryLayout.setHorizontalGroup(
            panelGroceryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGroceryLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblGrocery)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panelGroceryLayout.setVerticalGroup(
            panelGroceryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGroceryLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(lblGrocery)
                .addGap(38, 38, 38))
        );

        panelTravel.setBackground(new java.awt.Color(0, 0, 204));
        panelTravel.setForeground(new java.awt.Color(255, 255, 255));
        panelTravel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelTravel.setPreferredSize(new java.awt.Dimension(175, 175));
        panelTravel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTravelMouseClicked(evt);
            }
        });

        lblTravel.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lblTravel.setForeground(new java.awt.Color(255, 255, 255));
        lblTravel.setText("Travel");

        javax.swing.GroupLayout panelTravelLayout = new javax.swing.GroupLayout(panelTravel);
        panelTravel.setLayout(panelTravelLayout);
        panelTravelLayout.setHorizontalGroup(
            panelTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTravelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblTravel)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        panelTravelLayout.setVerticalGroup(
            panelTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTravelLayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(lblTravel)
                .addGap(24, 24, 24))
        );

        panelEntertain.setBackground(new java.awt.Color(0, 0, 204));
        panelEntertain.setForeground(new java.awt.Color(255, 255, 255));
        panelEntertain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEntertain.setPreferredSize(new java.awt.Dimension(175, 175));
        panelEntertain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEntertainMouseClicked(evt);
            }
        });

        lblEnt.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lblEnt.setForeground(new java.awt.Color(255, 255, 255));
        lblEnt.setText("Entertainment");

        javax.swing.GroupLayout panelEntertainLayout = new javax.swing.GroupLayout(panelEntertain);
        panelEntertain.setLayout(panelEntertainLayout);
        panelEntertainLayout.setHorizontalGroup(
            panelEntertainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntertainLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lblEnt)
                .addGap(21, 21, 21))
        );
        panelEntertainLayout.setVerticalGroup(
            panelEntertainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntertainLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(lblEnt)
                .addGap(30, 30, 30))
        );

        panelShopping.setBackground(new java.awt.Color(0, 0, 204));
        panelShopping.setForeground(new java.awt.Color(255, 255, 255));
        panelShopping.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelShopping.setPreferredSize(new java.awt.Dimension(175, 175));
        panelShopping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelShoppingMouseClicked(evt);
            }
        });

        lblShopping.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lblShopping.setForeground(new java.awt.Color(255, 255, 255));
        lblShopping.setText("Shopping");

        javax.swing.GroupLayout panelShoppingLayout = new javax.swing.GroupLayout(panelShopping);
        panelShopping.setLayout(panelShoppingLayout);
        panelShoppingLayout.setHorizontalGroup(
            panelShoppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShoppingLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblShopping)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelShoppingLayout.setVerticalGroup(
            panelShoppingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShoppingLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(lblShopping)
                .addGap(25, 25, 25))
        );

        panelOthers.setBackground(new java.awt.Color(0, 0, 204));
        panelOthers.setForeground(new java.awt.Color(255, 255, 255));
        panelOthers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOthers.setPreferredSize(new java.awt.Dimension(175, 175));
        panelOthers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOthersMouseClicked(evt);
            }
        });

        lblOthers.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lblOthers.setForeground(new java.awt.Color(255, 255, 255));
        lblOthers.setText("Others");

        javax.swing.GroupLayout panelOthersLayout = new javax.swing.GroupLayout(panelOthers);
        panelOthers.setLayout(panelOthersLayout);
        panelOthersLayout.setHorizontalGroup(
            panelOthersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOthersLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(lblOthers)
                .addGap(58, 58, 58))
        );
        panelOthersLayout.setVerticalGroup(
            panelOthersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOthersLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(lblOthers)
                .addGap(35, 35, 35))
        );

        panelEatout.setBackground(new java.awt.Color(0, 0, 204));
        panelEatout.setForeground(new java.awt.Color(255, 255, 255));
        panelEatout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEatout.setPreferredSize(new java.awt.Dimension(175, 175));
        panelEatout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEatoutMouseClicked(evt);
            }
        });

        lblEatout.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lblEatout.setForeground(new java.awt.Color(255, 255, 255));
        lblEatout.setText("Eatout");

        javax.swing.GroupLayout panelEatoutLayout = new javax.swing.GroupLayout(panelEatout);
        panelEatout.setLayout(panelEatoutLayout);
        panelEatoutLayout.setHorizontalGroup(
            panelEatoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEatoutLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblEatout)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelEatoutLayout.setVerticalGroup(
            panelEatoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEatoutLayout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(lblEatout)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelShopping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelEdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelEntertain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTravel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGrocery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEatout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelOthers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelShopping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTravel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEntertain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEatout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOthers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGrocery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //GlobalData.setCategorySelected(true);
        //this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void panelShoppingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelShoppingMouseClicked
        // TODO add your handling code here:
        //GlobalData.setCategory(lblShopping.getText());
        cCat=lblShopping.getText();
        System.out.println(lblShopping.getText());
        openCalculator();    
    }//GEN-LAST:event_panelShoppingMouseClicked

    private void panelTravelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTravelMouseClicked
        // TODO add your handling code here:
        cCat=lblTravel.getText();
        openCalculator();
    }//GEN-LAST:event_panelTravelMouseClicked

    private void panelBillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBillsMouseClicked
        // TODO add your handling code here:
        cCat=lblBills.getText();
        openCalculator();
    }//GEN-LAST:event_panelBillsMouseClicked

    private void panelHealthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHealthMouseClicked
        // TODO add your handling code here:
        cCat=lblHealth.getText();
        openCalculator();
    }//GEN-LAST:event_panelHealthMouseClicked

    private void panelEntertainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntertainMouseClicked
        // TODO add your handling code here:
        cCat=lblEnt.getText();
        openCalculator();
    }//GEN-LAST:event_panelEntertainMouseClicked

    private void panelEatoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEatoutMouseClicked
        // TODO add your handling code here:
        cCat=lblEatout.getText();
        openCalculator();
    }//GEN-LAST:event_panelEatoutMouseClicked

    private void panelEduMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEduMouseClicked
        // TODO add your handling code here:
        cCat=lblEducation.getText();
        openCalculator();
    }//GEN-LAST:event_panelEduMouseClicked

    private void panelGroceryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGroceryMouseClicked
        // TODO add your handling code here:
        cCat=lblGrocery.getText();
        openCalculator();
    }//GEN-LAST:event_panelGroceryMouseClicked

    private void panelOthersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOthersMouseClicked
        // TODO add your handling code here:
        cCat=lblOthers.getText();
        openCalculator();
    }//GEN-LAST:event_panelOthersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategorySelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategorySelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategorySelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategorySelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategorySelectionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JLabel lblBills;
    private javax.swing.JLabel lblEatout;
    private javax.swing.JLabel lblEducation;
    private javax.swing.JLabel lblEnt;
    private javax.swing.JLabel lblGrocery;
    private javax.swing.JLabel lblHealth;
    private javax.swing.JLabel lblOthers;
    private javax.swing.JLabel lblShopping;
    private javax.swing.JLabel lblTravel;
    private javax.swing.JPanel panelBills;
    private javax.swing.JPanel panelEatout;
    private javax.swing.JPanel panelEdu;
    private javax.swing.JPanel panelEntertain;
    private javax.swing.JPanel panelGrocery;
    private javax.swing.JPanel panelHealth;
    private javax.swing.JPanel panelOthers;
    private javax.swing.JPanel panelShopping;
    private javax.swing.JPanel panelTravel;
    // End of variables declaration//GEN-END:variables

    private void openCalculator() {
        InputCalculatorFrame frame=new InputCalculatorFrame(cCat,cResult,cDesc);
        frame.setVisible(true);
        this.dispose();
    }
}
