/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expenses.gui;

import com.sun.glass.events.KeyEvent;
import expenses.dao.CategoriesDAO;
import expenses.dao.UserInfoDAO;
import expenses.dao.UsersDAO;
import expenses.pojo.UserInfo;
import expenses.pojo.Users;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Maraxys
 */
public class RegistrationFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationFrame
     */
    private int cbAge,budget;
    private String uname,uGender,uid,pwd;
    private boolean result1,result2;
    
    public RegistrationFrame() {
        initComponents();
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblUserId = new javax.swing.JLabel();
        lblUserId1 = new javax.swing.JLabel();
        lblUserId2 = new javax.swing.JLabel();
        lblUserId3 = new javax.swing.JLabel();
        lblUserId4 = new javax.swing.JLabel();
        lblUserId5 = new javax.swing.JLabel();
        btnSaveRegister = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jrbMale = new javax.swing.JRadioButton();
        jrbFemale = new javax.swing.JRadioButton();
        txtPassword = new javax.swing.JPasswordField();
        txtRetypePwd = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtLoginId = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtBudget = new javax.swing.JTextField();
        lblUserId6 = new javax.swing.JLabel();
        jcAge = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserId.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblUserId.setForeground(new java.awt.Color(2, 119, 189));
        lblUserId.setText("PASSWORD");
        jPanel1.add(lblUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        lblUserId1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblUserId1.setForeground(new java.awt.Color(2, 119, 189));
        lblUserId1.setText("USERNAME");
        jPanel1.add(lblUserId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, 48));

        lblUserId2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblUserId2.setForeground(new java.awt.Color(2, 119, 189));
        lblUserId2.setText("LOGIN ID");
        jPanel1.add(lblUserId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, 53));

        lblUserId3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblUserId3.setForeground(new java.awt.Color(2, 119, 189));
        lblUserId3.setText("AGE");
        jPanel1.add(lblUserId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));

        lblUserId4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblUserId4.setForeground(new java.awt.Color(2, 119, 189));
        lblUserId4.setText("BUDGET");
        jPanel1.add(lblUserId4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, -1, -1));

        lblUserId5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblUserId5.setForeground(new java.awt.Color(2, 119, 189));
        lblUserId5.setText("RE-TYPE PASSWORD");
        jPanel1.add(lblUserId5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        btnSaveRegister.setBackground(new java.awt.Color(255, 0, 204));
        btnSaveRegister.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnSaveRegister.setForeground(new java.awt.Color(240, 240, 240));
        btnSaveRegister.setText("Count Me In");
        btnSaveRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnSaveRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 240, -1));

        btnBack.setBackground(new java.awt.Color(255, 0, 204));
        btnBack.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(240, 240, 240));
        btnBack.setText("BACK");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 31, 159, 49));

        buttonGroup1.add(jrbMale);
        jrbMale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbMale.setText("MALE");
        jrbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMaleActionPerformed(evt);
            }
        });
        jPanel1.add(jrbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        buttonGroup1.add(jrbFemale);
        jrbFemale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbFemale.setText("FEMALE");
        jrbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFemaleActionPerformed(evt);
            }
        });
        jPanel1.add(jrbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, -1));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 263, 40));
        jPanel1.add(txtRetypePwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 266, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 309, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 309, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 309, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 309, 10));

        jSeparator5.setBackground(new java.awt.Color(255, 0, 153));
        jSeparator5.setForeground(new java.awt.Color(236, 64, 122));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 575, 309, 10));
        jPanel1.add(txtLoginId, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 109, 263, 30));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 267, 33));

        txtBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBudgetActionPerformed(evt);
            }
        });
        txtBudget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBudgetKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBudgetKeyTyped(evt);
            }
        });
        jPanel1.add(txtBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 262, 30));

        lblUserId6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblUserId6.setForeground(new java.awt.Color(2, 119, 189));
        lblUserId6.setText("GENDER");
        jPanel1.add(lblUserId6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        jcAge.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jcAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50" }));
        jcAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcAgeActionPerformed(evt);
            }
        });
        jPanel1.add(jcAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRegisterActionPerformed
        // TODO add your handling code here:
        int inputValidity=validateInput();
        
        if(inputValidity==0) {
                JOptionPane.showMessageDialog(null, "Please fill all the required fields","Fill All Fields!",JOptionPane.ERROR_MESSAGE);
            }
            else if(inputValidity==-2){
                JOptionPane.showMessageDialog(null, "Password must be identical in both fields","Re-Type Passowrd!",JOptionPane.ERROR_MESSAGE);
            }
            else if(inputValidity==-1) {
                JOptionPane.showMessageDialog(null, "Login ID/Password must have minimum 6 characters","ID/Password too short!",JOptionPane.ERROR_MESSAGE);
            }
            else if(inputValidity==-3) {
                JOptionPane.showMessageDialog(null, "Enter values within 100-100000","Invalid Range",JOptionPane.ERROR_MESSAGE);
            }
            else{
                uGender=getGender();
                if(uGender==null){
                    JOptionPane.showMessageDialog(null, "Please select a Gender","Select One",JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                cbAge=getAge();
                if(cbAge==0){
                    JOptionPane.showMessageDialog(null, "Please select your age","Age not Found!",JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                uid=txtLoginId.getText();
                pwd=String.valueOf(txtPassword.getPassword());
                uname=txtUsername.getText();
                budget=Integer.parseInt(txtBudget.getText());
                
                Users u=new Users();
                    u.setUserId(uid);
                    u.setPassword(pwd);
                    
                UserInfo uinfo=new UserInfo();
                    uinfo.setUserId(uid);
                    uinfo.setName(uname);
                    uinfo.setGender(uGender);
                    uinfo.setAge(cbAge);
                    
                try{
                    result1=UsersDAO.userIdExists(uid);
                    if(!result1){
                        //JOptionPane.showMessageDialog(null, "Welcome to our App","Hello"+uid,JOptionPane.INFORMATION_MESSAGE);
                
                        try{
                            result2=UserInfoDAO.userNameExists(uname);
                                if(!result2){
                                    boolean a,b;
                                    a=UsersDAO.addUsers(u);
                                    b=UserInfoDAO.addUserInfo(uinfo);
                                    
                                    if(a&&b) {
                                        CategoriesDAO.addToCat(uid, budget);
                                        JOptionPane.showMessageDialog(null, "Your info has been added suceesfully..","Welcome to our app "+uname,JOptionPane.INFORMATION_MESSAGE);
                                        UserLoginFrame frame=new UserLoginFrame();
                                            frame.setVisible(true);
                                            this.dispose();
                                    }
                                    else {
                                    JOptionPane.showMessageDialog(null, "Your account could not be created","Sorry! Please try again!",JOptionPane.ERROR_MESSAGE);
                                    }
                                }
                                else{
                                    JOptionPane.showMessageDialog(null, "Please try another name","User name already exists",JOptionPane.ERROR_MESSAGE);
                                }        
                        }
                        catch(SQLException ex) {
                            JOptionPane.showMessageDialog(null, "Could not update user_info table ","SQL Exception",JOptionPane.ERROR_MESSAGE);
                            ex.printStackTrace();
                        }
                    }
                    
                    else{
                        JOptionPane.showMessageDialog(null, "Please input another User ID","User id already exists",JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }    
                catch(SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Could not update users table ","SQL Exception",JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }
                
                
                
            }
               
    }//GEN-LAST:event_btnSaveRegisterActionPerformed

    private void jrbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMaleActionPerformed

    private void jrbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbFemaleActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBudgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBudgetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        UserLoginFrame frame=new UserLoginFrame();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jcAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcAgeActionPerformed

    private void txtBudgetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBudgetKeyPressed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_txtBudgetKeyPressed

    private void txtBudgetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBudgetKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
            if(!(Character.isDigit(c))||c==KeyEvent.VK_BACKSPACE||c==KeyEvent.VK_DELETE){
                evt.consume();
            }
    }//GEN-LAST:event_txtBudgetKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSaveRegister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JComboBox<String> jcAge;
    private javax.swing.JRadioButton jrbFemale;
    private javax.swing.JRadioButton jrbMale;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JLabel lblUserId1;
    private javax.swing.JLabel lblUserId2;
    private javax.swing.JLabel lblUserId3;
    private javax.swing.JLabel lblUserId4;
    private javax.swing.JLabel lblUserId5;
    private javax.swing.JLabel lblUserId6;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtLoginId;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRetypePwd;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private int validateInput() {
        if(txtLoginId.getText().isEmpty()||txtUsername.getText().isEmpty()||txtPassword.getPassword().length==0||txtRetypePwd.getPassword().length==0||txtBudget.getText().isEmpty()) {
            return 0;
        }
        
        if(txtLoginId.getText().length()<6||txtPassword.getPassword().length<6) {
            return -1;
        }
        
        if(String.valueOf(txtPassword.getPassword()).equals(String.valueOf(txtRetypePwd.getPassword()))==false) {
            return -2;
        }
        
        if(txtBudget.getText().length()>5||txtBudget.getText().length()<3){
            return -3;
        }
        
        return 1;
    }

    private String getGender() {
        if(jrbMale.isSelected()){
            return jrbMale.getText();
        }
        if(jrbFemale.isSelected()){
            return jrbFemale.getText();
        }
        return null;
    }

    private int getAge() {
        int selectedIndex=jcAge.getSelectedIndex();
            if(selectedIndex==0) {
                return 0;
            }
            //System.out.println("Age"+jcAge.getSelectedItem());
            return (Integer.parseInt(jcAge.getSelectedItem().toString()));
    }
}
